name: Release

on:
  release:
    types: [published]
  workflow_dispatch:
  repository_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Publish to npm
      run : |
        npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
        npm publish --ignore-scripts --access public
      env :
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
